logging:
  level:
    dev.mbo: TRACE
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd'T'HH:mm:ss.SSSXXX}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m %clr({%X}){magenta}%n"

spring:
  kafka:
    bootstrap-servers: kraft1:9192,kraft2:9193,kraft3:9194