logging:
  level:
    dev.mbo: TRACE
    dev.mbo.serveradmin.server.db.history: WARN
    org.hibernate: WARN

spring:
  kafka:
    bootstrap-servers: kraft1:9192,kraft2:9193,kraft3:9194

app:
  task:
    db-history-cleanup:
      cron: "*/10 * * * * *" # every 10 seconds
      cutoff: 60
