apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - env:
            - name: PGDATA
              valueFrom:
                configMapKeyRef:
                  name: pgconfig
                  key: datadir
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: pgconfig
                  key: dbname
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: pgcreds
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgcreds
                  key: password
          image: postgres:16
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "admin", "-d", "sa-server1"]
            failureThreshold: 10
            periodSeconds: 1
            timeoutSeconds: 5
          name: postgres
          ports:
            - containerPort: 5432
              hostIP: 127.0.0.1
              hostPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
      hostname: postgres
      restartPolicy: Always
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data
